// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAheVZpXaxlxf_aN7-_VPEXUpjOFBSbfxs',
    appId: '1:191876170319:web:9ffe5bbab3a5e1603b203a',
    messagingSenderId: '191876170319',
    projectId: 'onlienshop-e51de',
    authDomain: 'onlienshop-e51de.firebaseapp.com',
    storageBucket: 'onlienshop-e51de.appspot.com',
    measurementId: 'G-7DMHH1M42Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxCcQR6Lz9Jq75DnrpZeMZQwZmeawhR_E',
    appId: '1:191876170319:android:87646928445689023b203a',
    messagingSenderId: '191876170319',
    projectId: 'onlienshop-e51de',
    storageBucket: 'onlienshop-e51de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrWI45PbhCntCe_ljhy303HyyXVi9M74Q',
    appId: '1:191876170319:ios:ac7f73e3ca6da5223b203a',
    messagingSenderId: '191876170319',
    projectId: 'onlienshop-e51de',
    storageBucket: 'onlienshop-e51de.appspot.com',
    iosBundleId: 'com.example.onlineshopcatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrWI45PbhCntCe_ljhy303HyyXVi9M74Q',
    appId: '1:191876170319:ios:353bd6bbff2ee88a3b203a',
    messagingSenderId: '191876170319',
    projectId: 'onlienshop-e51de',
    storageBucket: 'onlienshop-e51de.appspot.com',
    iosBundleId: 'com.example.onlineshopcatapp.RunnerTests',
  );
}
